language: cpp
sudo: false
dist: xenial
matrix:
  fast_finish: true
  include:
    - os: linux
      addons: &1
        apt:
          packages:
            - cmake
            - g++
            - gcc
            - libpython3.5-dev
            - python3.5-dev
    - os: osx

cache:
  timeout: 1000
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew

env:
  global:
    - LC_ALL="en_US.UTF-8"
    - LANG="en_US.UTF-8"
    - LANGUAGE="en_US.UTF-8"
    - PYTHONIOENCODING=UTF-8
    # Invalidate PYENV_ROOT
    - PYENV_ROOT=$HOME/fuffa

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export PYTHON3="/usr/bin/python3.5";
    else
      export PYTHON3="/usr/local/bin/python3";
    fi

install:
  - ./.scripts/travis/install.sh
  - pipenv install --python $PYTHON3
  - pipenv run python --version

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      test -n $CC && unset CC && export CC=gcc;
      test -n $CXX && unset CXX && export CXX=g++;
    else
      test -n $CC && unset CC && export CC=gcc;
      test -n $CXX && unset CXX && export CXX=g++;
    fi

script:
  - cmake -H. -Bbuild
  - cmake --build build -- VERBOSE=1
  # Testing
