language: cpp

sudo: false

dist: xenial

cache:
  timeout: 1000
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew

env:
  - WHICH=externalproject
  - WHICH=fetchcontent


matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++
            - gcc
      env:
        - PATH=$HOME/Deps/cmake/$CMAKE_VERSION/bin${PATH:+:$PATH}
    - os: osx

install:
  - ./.scripts/travis/install.sh
  - pipenv install --three
  - pipenv run python --version

before_script:
  - test -n $CC && unset CC && export CC=gcc;
  - test -n $CXX && unset CXX && export CXX=g++;

script:
  - cmake -H"$WHICH" -Bbuild
  - cmake --build build -- VERBOSE=1
  # Testing
