language: cpp

sudo: false

dist: xenial


cache:
  timeout: 1000
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew

matrix:
  fast_finish: true
  include:
    - os: linux
      python:
        - 3.7
      addons: &1
        apt:
          packages:
            - cmake
            - g++
            - gcc
    - os: linux
      python:
        - 3.6
      addons: *1
    - os: linux
      python:
        - 3.5
      addons: *1
    - os: linux
      python:
        - 3.4
      addons: *1
    - os: osx
      python:
        - 3.7
    - os: osx
      python:
        - 3.6
    - os: osx
      python:
        - 3.5
    - os: osx
      python:
        - 3.4

install:
  - ./.scripts/travis/install.sh
  - pipenv install --three
  - pipenv run python --version

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      test -n $CC && unset CC && export CC=gcc;
      test -n $CXX && unset CXX && export CXX=g++;
    else
      test -n $CC && unset CC && export CC=gcc;
      test -n $CXX && unset CXX && export CXX=g++;
    fi

script:
  - cmake -H. -Bbuild
  - cmake --build build -- VERBOSE=1
  # Testing
