language: cpp

sudo: false

dist: xenial

python:
  - 3.7
  - 3.6
  - 3.5
  - 3.4

cache:
  timeout: 1000
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew

matrix:
  fast_finish: true
  include:
    - os: linux
      addons: &1
        apt:
          packages:
            - cmake
            - g++
            - gcc
            - libpython3.5-dev
            - python3.5-dev
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export PYTHON3="/usr/bin/python3.5";
    else
      export PYTHON3="/usr/local/bin/python3";
    fi

install:
  - ./.scripts/travis/install.sh
  - pipenv install --three
  - pipenv run python --version

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      test -n $CC && unset CC && export CC=gcc;
      test -n $CXX && unset CXX && export CXX=g++;
    else
      test -n $CC && unset CC && export CC=gcc;
      test -n $CXX && unset CXX && export CXX=g++;
    fi

script:
  - cmake -H. -Bbuild
  - cmake --build build -- VERBOSE=1
  # Testing
