language: cpp

sudo: false

dist: xenial

cache:
  timeout: 1000
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew

env:
  - WHICH=externalproject
  - WHICH=fetchcontent

os:
  - linux
  - osx

addons:
  homebrew:
    packages:
      - gcc
      - cmake
      - pipenv
    update: true

matrix:
  fast_finish: true

before_install:
  - ./.scripts/travis/install.sh

install:
  - pipenv install --three
  - pipenv run python --version

before_script:
  - test -n $CC && unset CC && export CC=gcc;
  - test -n $CXX && unset CXX && export CXX=g++;
  - cmake --version

script:
  - export PATH=$HOME/Deps/cmake/$CMAKE_VERSION/bin${PATH:+:$PATH}
  - cd "$WHICH"
  - cmake -H. -Bbuild
  - cmake --build build -- VERBOSE=1
  - cd build
  - pipenv run ctest --output-on-failure --verbose
